import { PrismaPg } from "@prisma/adapter-pg"; import { PrismaClient } from "@prisma/client"; import { resolve } from "node:path"; import { enrichExtractedFrames } from "./frame-telemetry-enrichment.js";
export async function backfillMediaTelemetry(mediaId:string,database:PrismaClient,storageRoot=resolve(process.cwd(),"../api/storage")){
 const media=await database.mediaAsset.findUnique({where:{id:mediaId},include:{frames:{include:{taskPhoto:true}}}}); if(!media||media.kind!=="video")throw new Error("原视频不存在");
 const rows=media.frames.filter(f=>f.taskPhoto&&f.videoTimestampMs!==null).map(f=>({fileName:f.originalFileName,storagePath:resolve(storageRoot,f.storagePath.replace(/^storage\//,"")),fileSize:f.fileSize,timestampMs:f.videoTimestampMs!}));
 const result=await enrichExtractedFrames(resolve(storageRoot,media.storagePath.replace(/^storage\//,"")),rows); let updated=0;
 for(const frame of result.frames){if(!frame.telemetry)continue; const asset=media.frames.find(f=>f.videoTimestampMs===frame.timestampMs)!; const t=frame.telemetry; await database.$transaction([database.taskPhoto.update({where:{id:asset.taskPhoto!.id},data:{capturedAt:t.capturedAt,latitude:t.latitude,longitude:t.longitude,absoluteAltitudeMeters:t.absoluteAltitudeMeters,relativeAltitudeMeters:t.relativeAltitudeMeters}}),database.taskPhotoTelemetry.upsert({where:{taskPhotoId:asset.taskPhoto!.id},create:{id:`telemetry-${asset.taskPhoto!.id}`,taskPhotoId:asset.taskPhoto!.id,source:"dji_subtitle",sourceTimestampMs:t.timestampMs,matchOffsetMs:t.matchOffsetMs,capturedAt:t.capturedAt,latitude:t.latitude,longitude:t.longitude,relativeAltitudeMeters:t.relativeAltitudeMeters,absoluteAltitudeMeters:t.absoluteAltitudeMeters,gimbalYawDegrees:t.gimbalYawDegrees,gimbalPitchDegrees:t.gimbalPitchDegrees,gimbalRollDegrees:t.gimbalRollDegrees,focalLengthMillimeters:t.focalLengthMillimeters,digitalZoomRatio:t.digitalZoomRatio},update:{sourceTimestampMs:t.timestampMs,matchOffsetMs:t.matchOffsetMs,capturedAt:t.capturedAt,latitude:t.latitude,longitude:t.longitude,relativeAltitudeMeters:t.relativeAltitudeMeters,absoluteAltitudeMeters:t.absoluteAltitudeMeters,gimbalYawDegrees:t.gimbalYawDegrees,gimbalPitchDegrees:t.gimbalPitchDegrees,gimbalRollDegrees:t.gimbalRollDegrees,focalLengthMillimeters:t.focalLengthMillimeters,digitalZoomRatio:t.digitalZoomRatio}})]);updated++;}
 return {updated,...result.stats};
}
if(process.argv[1]?.endsWith("telemetry-backfill.ts")){const mediaId=process.argv[process.argv.indexOf("--media-id")+1]; if(!mediaId)throw new Error("请提供 --media-id"); const url=process.env.DATABASE_URL||"postgresql://xunjianbao:xunjianbao-local-dev@127.0.0.1:5432/xunjianbao?schema=public"; const db=new PrismaClient({adapter:new PrismaPg({connectionString:url})}); backfillMediaTelemetry(mediaId,db).then(r=>console.log(JSON.stringify(r))).finally(()=>db.$disconnect());}
